### ISSUE TITLE
Keeps Getting Disconnected

### ISSUE THREAD

**Issue by macjabeth** [austinmiller/aug#46]
I've tried logging in to Akanbar and it disconnects me the moment I send anything to the MUD.

When trying to connect to Avalon it just connects and disconnects immediately.

I'm on Elementary OS, installed AugustMC with the .deb file.

**Comment by austinmiller** [comment]
I'll test this myself tonight and see if I can replicate.  Can you try connecting to aardmud and see if you can hold a connection there?

**Comment by austinmiller** [comment]
I was able to repro, I'm working on it.

**Comment by austinmiller** [comment]
Fixed in https://github.com/austinmiller/augustmc/commit/5425ece7c7b82faa25c1f18b9598cac8e423c827  Since this is such a big problem for muds that use telnet GA, going to cut a new release tonight.

**Comment by austinmiller** [comment]
Here's the release: https://github.com/austinmiller/augustmc/releases/tag/2017.2

Thanks for finding the bug!  I'm going to work on telnet compatibility this weekend across multiple mud servers to make sure the client is doing the right thing.
